//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CalcoloCodiceFiscale.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CalcoloCodiceFiscale.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A074
        ///A109
        ///A117
        ///A157
        ///A218
        ///A221
        ///A222
        ///A275
        ///A282
        ///A295
        ///A405
        ///A518
        ///A525
        ///A584
        ///A587
        ///A590
        ///A591
        ///A599
        ///A607
        ///A625
        ///A651
        ///A673
        ///A734
        ///A853
        ///A910
        ///A941
        ///A990
        ///B003
        ///B015
        ///B021
        ///B024
        ///B075
        ///B121
        ///B171
        ///B205
        ///B209
        ///B216
        ///B225
        ///B232
        ///B278
        ///B279
        ///B284
        ///B297
        ///B305
        ///B350
        ///B435
        ///B462
        ///B512
        ///B588
        ///B592
        ///B605
        ///B628
        ///B637
        ///B705
        ///B733
        ///B762
        ///B777
        ///B791
        ///B867
        ///B953
        ///B955
        ///B960
        ///C045
        ///C048
        ///C133
        ///C241
        ///C307
        ///C369
        ///C404
        ///C487
        ///C497
        ///C505
        ///C564
        ///C604
        ///C610
        ///C624
        ///C627
        ///C629
        ///C639
        ///C655
        ///C665
        ///C679
        ///C711
        ///C715
        ///C722
        ///C7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string codCatastale {
            get {
                return ResourceManager.GetString("codCatastale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agliè
        ///Airasca
        ///Ala di Stura
        ///Albiano d&apos;Ivrea
        ///Almese
        ///Alpette
        ///Alpignano
        ///Andezeno
        ///Andrate
        ///Angrogna
        ///Arignano
        ///Avigliana
        ///Azeglio
        ///Bairo
        ///Balangero
        ///Baldissero Canavese
        ///Baldissero Torinese
        ///Balme
        ///Banchette
        ///Barbania
        ///Bardonecchia
        ///Barone Canavese
        ///Beinasco
        ///Bibiana
        ///Bobbio Pellice
        ///Bollengo
        ///Borgaro Torinese
        ///Borgiallo
        ///Borgofranco d&apos;Ivrea
        ///Borgomasino
        ///Borgone Susa
        ///Bosconero
        ///Brandizzo
        ///Bricherasio
        ///Brosso
        ///Brozolo
        ///Bruino
        ///Brusasco
        ///Bruzolo
        ///Buriasco
        ///Burolo
        ///Busano
        ///Bussoleno
        ///Buttigliera Alta
        ///Caf [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string listacomuni {
            get {
                return ResourceManager.GetString("listacomuni", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albania	201
        ///Andorra	202
        ///Austria	203
        ///Belgio	206
        ///Bulgaria	209
        ///Danimarca	212
        ///Finlandia	214
        ///Francia	215
        ///Germania	216
        ///Regno Unito	219
        ///Grecia	220
        ///Irlanda	221
        ///Islanda	223
        ///Liechtenstein	225
        ///Lussemburgo	226
        ///Malta	227
        ///Monaco	229
        ///Norvegia	231
        ///Paesi Bassi	232
        ///Polonia	233
        ///Portogallo	234
        ///Romania	235
        ///San Marino	236
        ///Spagna	239
        ///Svezia	240
        ///Svizzera	241
        ///Ucraina	243
        ///Ungheria	244
        ///Federazione russa	245
        ///Stato della Città del Vaticano	246
        ///Estonia	247
        ///Lettonia	248
        ///Lituania	249
        ///Croazia	250
        ///Slovenia	 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string nazioni {
            get {
                return ResourceManager.GetString("nazioni", resourceCulture);
            }
        }
    }
}
